/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCronRouteImport } from './routes/api/cron'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiEoChangeImageRouteImport } from './routes/api/eo/change-image'
import { Route as ApiEoSarRouteImport } from './routes/api/eo/sar'
import { Route as ApiEoSwirRouteImport } from './routes/api/eo/swir'
import { Route as ApiSesCatalogRouteImport } from './routes/api/ses/catalog'
import { Route as ApiSesVolcanoRouteImport } from './routes/api/ses/volcano'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRoute = ApiCronRouteImport.update({
  id: '/api/cron',
  path: '/api/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEoChangeImageRoute = ApiEoChangeImageRouteImport.update({
  id: '/api/eo/change-image',
  path: '/api/eo/change-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEoSarRoute = ApiEoSarRouteImport.update({
  id: '/api/eo/sar',
  path: '/api/eo/sar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEoSwirRoute = ApiEoSwirRouteImport.update({
  id: '/api/eo/swir',
  path: '/api/eo/swir',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSesCatalogRoute = ApiSesCatalogRouteImport.update({
  id: '/api/ses/catalog',
  path: '/api/ses/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSesVolcanoRoute = ApiSesVolcanoRouteImport.update({
  id: '/api/ses/volcano',
  path: '/api/ses/volcano',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/cron': typeof ApiCronRoute
  '/api/health': typeof ApiHealthRoute
  '/api/eo/change-image': typeof ApiEoChangeImageRoute
  '/api/eo/sar': typeof ApiEoSarRoute
  '/api/eo/swir': typeof ApiEoSwirRoute
  '/api/ses/catalog': typeof ApiSesCatalogRoute
  '/api/ses/volcano': typeof ApiSesVolcanoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/cron': typeof ApiCronRoute
  '/api/health': typeof ApiHealthRoute
  '/api/eo/change-image': typeof ApiEoChangeImageRoute
  '/api/eo/sar': typeof ApiEoSarRoute
  '/api/eo/swir': typeof ApiEoSwirRoute
  '/api/ses/catalog': typeof ApiSesCatalogRoute
  '/api/ses/volcano': typeof ApiSesVolcanoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/cron': typeof ApiCronRoute
  '/api/health': typeof ApiHealthRoute
  '/api/eo/change-image': typeof ApiEoChangeImageRoute
  '/api/eo/sar': typeof ApiEoSarRoute
  '/api/eo/swir': typeof ApiEoSwirRoute
  '/api/ses/catalog': typeof ApiSesCatalogRoute
  '/api/ses/volcano': typeof ApiSesVolcanoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/cron'
    | '/api/health'
    | '/api/eo/change-image'
    | '/api/eo/sar'
    | '/api/eo/swir'
    | '/api/ses/catalog'
    | '/api/ses/volcano'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/cron'
    | '/api/health'
    | '/api/eo/change-image'
    | '/api/eo/sar'
    | '/api/eo/swir'
    | '/api/ses/catalog'
    | '/api/ses/volcano'
  id:
    | '__root__'
    | '/'
    | '/api/cron'
    | '/api/health'
    | '/api/eo/change-image'
    | '/api/eo/sar'
    | '/api/eo/swir'
    | '/api/ses/catalog'
    | '/api/ses/volcano'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCronRoute: typeof ApiCronRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiEoChangeImageRoute: typeof ApiEoChangeImageRoute
  ApiEoSarRoute: typeof ApiEoSarRoute
  ApiEoSwirRoute: typeof ApiEoSwirRoute
  ApiSesCatalogRoute: typeof ApiSesCatalogRoute
  ApiSesVolcanoRoute: typeof ApiSesVolcanoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron': {
      id: '/api/cron'
      path: '/api/cron'
      fullPath: '/api/cron'
      preLoaderRoute: typeof ApiCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/eo/change-image': {
      id: '/api/eo/change-image'
      path: '/api/eo/change-image'
      fullPath: '/api/eo/change-image'
      preLoaderRoute: typeof ApiEoChangeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/eo/sar': {
      id: '/api/eo/sar'
      path: '/api/eo/sar'
      fullPath: '/api/eo/sar'
      preLoaderRoute: typeof ApiEoSarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/eo/swir': {
      id: '/api/eo/swir'
      path: '/api/eo/swir'
      fullPath: '/api/eo/swir'
      preLoaderRoute: typeof ApiEoSwirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ses/catalog': {
      id: '/api/ses/catalog'
      path: '/api/ses/catalog'
      fullPath: '/api/ses/catalog'
      preLoaderRoute: typeof ApiSesCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ses/volcano': {
      id: '/api/ses/volcano'
      path: '/api/ses/volcano'
      fullPath: '/api/ses/volcano'
      preLoaderRoute: typeof ApiSesVolcanoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCronRoute: ApiCronRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiEoChangeImageRoute: ApiEoChangeImageRoute,
  ApiEoSarRoute: ApiEoSarRoute,
  ApiEoSwirRoute: ApiEoSwirRoute,
  ApiSesCatalogRoute: ApiSesCatalogRoute,
  ApiSesVolcanoRoute: ApiSesVolcanoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
